'use client';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { Menu, Star } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { INSTRUCTORS, NAV_LINKS, PROGRAMS, TESTIMONIALS } from '@/lib/constants';
import { GrainOverlay } from '@/components/shared/GrainOverlay';
import { SectionHeader } from '@/components/shared/SectionHeader';
import { StatPill } from '@/components/shared/StatPill';

export function PageSections() { const [open,setOpen]=useState(false); const hero='https://images.unsplash.com/photo-1515777315835-281b94c9589f?auto=format&fit=crop&w=1800&q=80';
return <><GrainOverlay /><header className='sticky top-0 z-50 border-b border-transparent bg-bg/70 backdrop-blur'><nav className='mx-auto flex max-w-7xl items-center justify-between px-6 py-4'><a href='#' className='text-2xl font-black italic'>STUNTX</a><div className='hidden gap-6 md:flex'>{NAV_LINKS.map(l=><a key={l.href} href={l.href}>{l.label}</a>)}</div><Button asChild className='hidden md:inline-flex'><a href='#contact'>ENROLL NOW</a></Button><button onClick={()=>setOpen(!open)} className='md:hidden' aria-label='Open menu'><Menu /></button></nav>{open&&<div className='md:hidden bg-surface p-6'>{NAV_LINKS.map(l=><a className='block py-2' key={l.href} href={l.href}>{l.label}</a>)}</div>}</header>
<main>
<section className='relative min-h-screen'><Image src={hero} alt='Bike stunt' fill className='object-cover opacity-30'/><div className='relative mx-auto max-w-7xl px-6 pt-32'><motion.h1 initial='hidden' animate='show' variants={{hidden:{},show:{transition:{staggerChildren:0.12}}}} className='text-6xl md:text-8xl font-black italic uppercase'>{['MASTER','THE','MACHINE.'].map((w,i)=><motion.span key={i} variants={{hidden:{opacity:0,y:20},show:{opacity:1,y:0}}} className={w==='MASTER'?'text-accent mr-4':'mr-4'}>{w}</motion.span>)}</motion.h1><p className='mt-6 max-w-2xl text-muted'>Pune&apos;s premier bike stunt training academy. Learn wheelies, stoppies, and full-control riding from certified pros — on a closed, safe track.</p><div className='mt-8 flex gap-3'><Button asChild><a href='#contact'>BOOK A TRIAL SESSION</a></Button><Button variant='ghost'>WATCH SHOWREEL</Button></div><div className='mt-16 grid grid-cols-2 md:grid-cols-4 gap-3'>{['500+ RIDERS TRAINED','8 YEARS','100% SAFETY RECORD','CERTIFIED INSTRUCTORS'].map(s=><StatPill key={s} label={s}/>)}</div></div></section>
<section className='mx-auto grid max-w-7xl gap-8 px-6 py-20 md:grid-cols-2'><div className='relative h-96'>{/* TODO: replace with actual StuntX photo */}<Image src='https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=80' alt='training' fill className='object-cover' /></div><div><SectionHeader kicker='01 / ABOUT' title="WE DON'T DO RECKLESS. WE DO RELENTLESS."/><p className='text-muted'>We train riders to command the bike, not gamble with it. Every drill happens inside a controlled, closed facility.</p></div></section>
<section id='programs' className='bg-surface py-20'><div className='mx-auto max-w-7xl px-6'><SectionHeader kicker='02 / TRAINING' title='PROGRAMS BUILT FOR PROGRESSION'/><div className='grid gap-4 md:grid-cols-2'>{PROGRAMS.map(p=><motion.article whileHover={{scale:1.02}} key={p.title} className='border border-borderline p-6 hover:border-accent hover:shadow-glow'><p className='text-accent'>{p.number}</p><h3 className='text-2xl font-bold italic'>{p.title}</h3><p>{p.duration}</p><ul className='my-4 list-disc pl-5 text-muted'>{p.skills.map(s=><li key={s}>{s}</li>)}</ul><p>{p.price} <span className='text-xs text-muted'>(TODO: update with real value)</span></p></motion.article>)}</div></div></section>
<section id='track' className='py-20'><div className='mx-auto max-w-7xl px-6'><SectionHeader kicker='03 / TRACK' title='CONTROLLED. MONITORED. RACE-READY.'/><div className='relative h-[420px]'>{/* TODO: replace with actual StuntX photo */}<Image src='https://images.unsplash.com/photo-1610374792793-f016b77ca51a?auto=format&fit=crop&w=1600&q=80' alt='track' fill className='object-cover'/></div></div></section>
<section id='instructors' className='py-20 bg-surface'><div className='mx-auto max-w-7xl px-6'><SectionHeader kicker='04 / INSTRUCTORS' title='COACHED BY PROS'/><div className='grid md:grid-cols-4 gap-4'>{INSTRUCTORS.map((i,idx)=><article key={i.name} className='border p-4'><div className='relative h-56 grayscale hover:grayscale-0'>{/* TODO: replace with actual StuntX photo */}<Image src={`https://placehold.co/600x600?text=Coach+${idx+1}`} alt={i.name} fill className='object-cover'/></div><h3 className='mt-3 font-bold'>{i.name}</h3><p className='text-sm text-muted'>{i.title} • {i.experience}</p></article>)}</div></div></section>
<section id='gallery' className='py-20'><div className='mx-auto max-w-7xl px-6'><SectionHeader kicker='05 / GALLERY' title='MOMENTS AT REDLINE'/><div className='grid grid-cols-2 md:grid-cols-7 gap-3'>{Array.from({length:7}).map((_,i)=><div key={i} className='relative h-40 md:h-60 overflow-hidden border'>{/* TODO: replace with actual StuntX photo */}<Image src={`https://placehold.co/800x600?text=Shot+${i+1}`} alt={`gallery ${i+1}`} fill className='object-cover hover:scale-105 transition'/></div>)}</div></div></section>
<section className='overflow-hidden border-y py-8'><motion.div animate={{x:['0%','-50%']}} transition={{duration:18, repeat:Infinity, ease:'linear'}} className='whitespace-nowrap text-4xl italic font-black'>WHEELIES • STOPPIES • BURNOUTS • DRIFTS • CIRCLE WHEELIES • 12 O&apos;CLOCK • ROLLING BURNOUT • CHRIST AIR • — </motion.div></section>
<section className='py-20 bg-surface'><div className='mx-auto max-w-7xl px-6'><SectionHeader kicker='06 / TESTIMONIALS' title='RIDER RESULTS'/><div className='grid md:grid-cols-3 gap-4'>{TESTIMONIALS.map(t=><article key={t.name} className='border p-5'><div className='flex'>{Array.from({length:5}).map((_,i)=><Star key={i} className='h-4 w-4 fill-warning text-warning'/>)}</div><p className='my-3'>{t.quote}</p><p className='text-sm text-muted'>{t.name} — {t.meta}</p></article>)}</div></div></section>
<section className='bg-accent p-10 text-black text-center'><h3 className='text-4xl font-black italic'>READY TO RIDE?</h3><Button className='mt-4 bg-black text-white' asChild><a href='#contact'>BOOK A FREE TRIAL</a></Button></section>
<section id='contact' className='py-20'><div className='mx-auto grid max-w-7xl gap-8 px-6 md:grid-cols-2'><form action='/api' className='space-y-3'>{['Name','Phone','Email','Age'].map(f=><input key={f} placeholder={f} className='w-full border bg-transparent p-3'/>) }<select className='w-full border bg-bg p-3'><option>None</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><textarea className='w-full border bg-transparent p-3' placeholder='Message'/><Button type='button' onClick={()=>{console.log('TODO: wire enrollment backend')}}>SUBMIT ENROLLMENT</Button></form><aside><p className='text-muted'>TODO: update with real value — Pune address, phone, email.</p><iframe title='Map placeholder' className='mt-4 h-64 w-full border' src='https://maps.google.com/maps?q=Pune&t=&z=13&ie=UTF8&iwloc=&output=embed' /></aside></div></section>
</main><footer className='border-t py-10 text-center text-sm text-muted'>© 2026 StuntX Academy. All rights reserved. Stunt riding is dangerous. Closed tracks only.</footer></>;
}
